Week six
BijayPuma/WeeklyProgrammingAssignments pull request #8
Opened 2024-03-04 11:01 UTC by BijayPuma

2024-03-06 05:21 UTC, maniramezan requested changes
Looks like you have also removed "weekfive" folder in this PR, not sure if that was intentional or not. Also, the example missing the default behavior for user to tap each row and be able to edit is not available in this example. Would you mind updating the code sample to also include the ability to tap at each row and edit?

2024-03-06 05:21 UTC, maniramezan commented on Homework6-start/Homework6.xcodeproj/project.pbxproj
Looks like you're copying and re-using previous folders, git is considering these as renames, making a separate copy could help with preventing this

2024-03-06 05:21 UTC, maniramezan commented on Homework6-start/Homework6/View/NewTaskButton.swift
It's recommended not to include any commented code in any PR, you can just delete it

2024-03-06 05:21 UTC, maniramezan commented on Week5Homework
Why does this show up as delete? Is this intentional to remove this folder?

2024-03-06 18:59 UTC, BijayPuma commented on Week5Homework
I created 3 branch for week5, I deleted 2(were not working) of them and kept only last one I created "WeekFive".

2024-03-06 19:20 UTC, BijayPuma commented on Homework6-start/Homework6/View/NewTaskButton.swift
added navigationlink on each row. Now user can tap each row and be able to edit.

2024-03-07 06:03 UTC, maniramezan approved these changes
Grade: Pass (Meets expectation)

Nice job on cool animation and creating re-usable views

2024-03-09 08:14 UTC, merged